# Generated by Django 3.1.4 on 2020-12-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True, max_length=400, null=True)),
                ('design', models.BooleanField(blank=True, default=False, null=True)),
                ('developing', models.BooleanField(blank=True, default=False, null=True)),
                ('piloting', models.BooleanField(blank=True, default=False, null=True)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
